replicaCount: 1

image: lscr.io/linuxserver/retroarch:latest
imagePullPolicy: IfNotPresent

service:
  httpPort: 3000
  httpsPort: 3001

retroarch:
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  customUser: ""
  password: ""
  title: "RetroArch"
  pixelfluxWayland: "false"

persistence:
  size: 10Gi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "4"
    memory: 4Gi

uds:
  host: retroarch
  gateway: tenant

additionalNetworkAllow: []
