replicaCount: 1

image: "###ZARF_CONST_RETROARCH_IMAGE###"
imagePullPolicy: IfNotPresent

service:
  httpPort: 3000
  httpsPort: 3001

retroarch:
  puid: "###ZARF_VAR_RETROARCH_PUID###"
  pgid: "###ZARF_VAR_RETROARCH_PGID###"
  tz: "###ZARF_VAR_RETROARCH_TZ###"
  customUser: "###ZARF_VAR_RETROARCH_CUSTOM_USER###"
  password: "###ZARF_VAR_RETROARCH_PASSWORD###"
  title: "RetroArch"
  pixelfluxWayland: "false"

persistence:
  size: "###ZARF_VAR_RETROARCH_STORAGE_SIZE###"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "4"
    memory: 4Gi

uds:
  host: retroarch
  gateway: tenant

additionalNetworkAllow: []
